import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navigator from '../components/navigation/navigator';
import { ViewTransitions } from 'next-view-transitions';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'VehiClean',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navigator />
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
